spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/server
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

# spring.datasource.url=jdbc:mysql://localhost:3306/server
# spring.datasource.username=root
# spring.datasource.password=
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect